### ISSUE TITLE
Fail to retrieve information

### ISSUE THREAD

**Issue by caiovernaglia** [VictorGrycuk/StreamDeck-KeePass#9] opened 2021-12-02 19:40 UTC
I'm unable to retrieve any information from my KeePass DB.
Log shows me this info:

2021-12-02 16:34:47.4490|INFO|BarRaider.SdTools.Logger|The file version is unsupported.
A newer KeePass version is required to open this file.

I'm running the latest version of KeePass 2.49

Any hints on what's going?
Thanks

**Comment by VictorGrycuk** [comment] 2021-12-02 23:35
Thank you @caiovernaglia for reporting the issue.
I will try to reproduce on my side and I will get back to you as soon as I can.

**Comment by VictorGrycuk** [comment] 2021-12-03 02:49
@caiovernaglia I have not been able to reproduce the issue.
I created a new `.kdbx` using KeePass 2.49, and I was able to retrieve the password.

A few questions:
1. Do you have any issues using the KeePass application?
1. Was the db created using the latest version of KeePass?
1. If you create a brand-new db, does the problem persist? If so, can you attach the newly created db?

As far as I know, they haven't introduced any change in the kdbx file format, but I want to be sure that the KeePassLib that this plugin uses has not become obsolete.

Thanks.

**Comment by VictorGrycuk** [comment] 2022-01-23 23:40
I will close the issue, reopen it if you need further assistant.

**Comment by Redirts** [comment] 2022-07-22 17:43
I also have this issue. How can I tell what is the version of the database?
I am using 2.51.1 (64 bits)

**Comment by VictorGrycuk** [comment] 2022-07-25 01:38
Hi @Redirts,
Was the `.kdbx` file created using the `2.51.1` version of KeePass?

**Comment by Redirts** [comment] 2022-07-26 18:55
Hi @VictorGrycuk I exported my current database to 2.x format and tried using that but I get the same error on the logs.
I then created a new database from scratch and created a dummy entry but I still the same error

**Comment by VictorGrycuk** [comment] 2022-07-28 02:19
Thank you for the information, @Redirts. I still can't reproduce the issue. 
This plugin is using the `KeePassLib.dll` version [2.30](https://www.nuget.org/packages/KeePassLib/), and while it is several years old, it seems to be the latest version of that library. However, I found that the `KeePass.exe` can be used as a replacement of the library, which is rather convenient.

I made a quick update, replacing the dll library with the exe file, and it worked on my side.
Please download [this version](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/v1.6.0-beta) and let me know if it fixes the issue for you.

**Comment by Redirts** [comment] 2022-07-28 12:58
Hey Victor. Thanks for the update. I will try that later and let you know.
Which version of keepass.exe are you testing with? Maybe it could be related. I am using 2.51.1

**Comment by Redirts** [comment] 2022-07-28 13:03
Actually Victor, I had time just now and tested it and it works!
Only problem I have now is that I am trying to retrieve a password field that has a field reference {TIMEOTP} and it is not converting it to my OTP code :-(

**Comment by VictorGrycuk** [comment] 2022-07-28 13:21
@Redirts Thank you for the info!
To be honest, it's the first time I hear about the `{TIMEOTP}` placeholder. So I am not sure if it's compatible with the library or the plugin. I will have to investigate it further.

Can you retrieve anything else correctly? If so, I can (re)close this issue, and open a new one to keep track of the new feature/implementation.

**Comment by Redirts** [comment] 2022-07-28 14:53
It's a way to generate one-time password tokens like the ones you can obtain with Microsoft authenticator or authy for extra login security.

Keepass has a feature to also generate OTPs which is handy.
https://keepass.info/help/base/placeholders.html#otp

It would be great (don't know if possible/effort) for keepass to give you the translated placeholder/field reference with the real value

Another use I give to placeholders/field references is having one password value in one keepass entry and then using a field reference of that password entry in another keepass entry, that way if I change the password in one place I don't have to update all the other entries.

**Closed as completed** 2022-07-28 21:53 UTC

**Comment by VictorGrycuk** [comment] 2022-07-28 21:55
I like the idea, I would like to add the feature to the plugin.
However, I need to research if the library offers such capabilities, and I won't be able to do it until mid next week. But I will let you know as soon as I have news about it.

I created a new issue and I will close this one as the original problem was solved.
